mod 'cargomedia/cm',
  :git => 'git@github.com:cargomedia/puppet-cm.git'

mod 'cargomedia/php5',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/php5'

mod 'cargomedia/environment',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/environment'

mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'feedlabs/cayley',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/cayley'

mod 'feedlabs/feedify',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/feedify'

mod 'feedlabs/neo4j',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/neo4j'
